services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # pas de port exposé ici : c'est servi via nginx
    networks:
      - ft_transcendance
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # plus de mapping 3002:3002 ici
    ports:
      - "8002:8002"       # votre API REST si besoin
    networks:
      - ft_transcendance
    restart: always

  ws-server:
    build:
      context: ./frontend/pong-server
      dockerfile: Dockerfile
    ports:
      - "3003:3003"       # unique mapping pour le WS
    networks:
      - ft_transcendance
    restart: always

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"         # HTTP → redirect HTTPS
      - "8444:443"        # HTTPS + WSS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ft_transcendance
    restart: always

networks:
  ft_transcendance:
    driver: bridge
