version: '3.8'

services:
  frontend:
    container_name: frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - ft_transcendance
    depends_on:
      - db
    restart: always

  backend:
    container_name: backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"      # WebSocket
    networks:
      - ft_transcendance
    depends_on:
      - db
    restart: always

  db:
    container_name: DataBase
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE:      ${MARIADB_DATABASE}
      MARIADB_USER:          ${MARIADB_USER}
      MARIADB_PASSWORD:      ${MARIADB_PASSWORD}
    networks:
      - ft_transcendance
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    container_name: nginx
    env_file:
      - .env
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"          # HTTP → redirigé vers HTTPS
      - "8443:443"        # HTTPS + WSS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - ft_transcendance
    restart: always

volumes:
  db_data:

networks:
  ft_transcendance:
    driver: bridge
